export const Messages = {
    TokenNotFound: "Token is not found.",
    TokenInvalid: "Token is invalid.",
    UserNotAdmin: "User is not an admin.",
    ErrorGetAllData: "An error occurred while fetching data.",
    ErrorDeletingUser: "An error occurred while deleting user.",
    ErrorEncodingToken: "An error occurred while encoding token.",
    UserNotFound: "Invalid Credentials. User not found.",
    IncorrectPWD: "Invalid Credentials. Incorrect password.",
    LoginError: "An error occurred during login.",
    UserExists: "User already exists.",
    PasswordRequired: "Password is required.",
    RegisterationError: "Registration error:",
    ErrorCreatingEndpoint: "An error occurred while creating endpoint.",
    ErrorIncrementingEndpoint: "An error occurred while incrementing endpoint count.",
    ErrorUpdatingStory: "An error occurred while updating story.",
    ErrorDeletingStory: "An error occurred while deleting story.",
    ErrorDecreasingApiUsage: "An error occurred while updating api usage.",
    ErrorFetchingUser: "An error occurred while fetching user.",
    ErrorUpdatingUser: "An error occurred while updating user.",
    ErrorFetchingRole: "An error occurred while fetching role.",
    ErrorFetchingApiUsage: "An error occurred while fetching api usage.",
    ErrorFetchingStory: "An error occurred while fetching story.",
    ErrorCreatingStory: "An error occurred while creating story.",

    MongoDbConnectionError: "MongoDB connection error:",

    MongoDBConnected: "MongoDB connected",
    StoryUpdated: "Story updated successfully.",
    StoryDeleted: "Story deleted successfully.",
    ErrorFetchingUsers: "An error occurred while fetching users.",
    UserDeleted: "User deleted successfully.",
    LogoutSuccess: "Logged out successfully",
    LoginSuccess: "Logged in successfully",
    LoginFailed: "Login failed",
    AllFieldsRequired: "All fields are required",
    UserRegister: "User registered successfully",
    RegisterationError: "Registration failed",
    GeneratePrompt_Opening: "(NOTE: Do not include the story in your response please) Continue this story ",
    GeneratePrompt_Closing: " and then place the new input after Next:",
    Listening: "Server is listening on port "
}
  